### ISSUE TITLE
bug because of a missing feature: SAMD floating point formatting by sprintf ("%f") is missing

### ISSUE THREAD

**Issue by dsyleixa** [arduino/ArduinoCore-samd#407]
other than to Arduino Due (ATSAM3X8E) and ESP8266/ESP32, for SAMD the floating point formatting by sprintf (str,"%f",fvar) is missing,
both for fp32 (float) and for fp64(double).

could that please be fixed by default for all SAMD cores?

PS,
just to mention:
The required Arduino implementation must not be limited by INT32_MAX size dimensions for predecimal digits.

**Comment by facchinm** [comment]
Should be solved by [beta](https://github.com/arduino/ArduinoCore-samd/tree/beta) branch which uses `arm-none-eabi-gcc-7-2017q4`

**Comment by dsyleixa** [comment]
AFAICS, the Beta Branch is featuring just MKR1000 and Vidor4000? (CMIIW)
what about M0/Zero and M4/SAMD51 ?

**Comment by facchinm** [comment]
We don't officially support M4 (D51) so you should ask Adafruit/ any 3rd party core supporting it.
The Beta branch supports all Arduino M0 boards, you just need to delete `boards.txt` and rename `boards.txt.disabled` into `boards.txt` (this will be the default once it becomes official).

**Comment by dsyleixa** [comment]
I already contacted Adafruit, they stated it's a Arduino SAMD core issue:
https://forums.adafruit.com/viewtopic.php?f=57&t=151197#p747810

**Comment by dsyleixa** [comment]
PS,
after having changed the boards.txt, the Adafruit M4 port is greyed out and the board cannot be detected any more.
Deleting the beta boards doesn't fix it any more, SAMD51 is not accesable at all!

**Comment by facchinm** [comment]
> after having changed the boards.txt, the Adafruit M4 port is greyed out and the board cannot be detected any more.
You needed to change the boards.txt in Beta folder; independent cores are not affected by other cores change, so the disappearing board must be due to something else

**Comment by dsyleixa** [comment]
I see, perhaps it's due to a coincidental simultaneous issue.

**Comment by sandeepmistry** [comment]
@facchinm can this be closed not that the toolchain was updated?

**Comment by dsyleixa** [comment]
is
sprintf (str,"%f",fvar) 
now available for M4 MCUs by default, just like for M3 Due?

**Comment by sandeepmistry** [comment]
This core only supports the SAMD21 Cortex-M0 based boards.

**Comment by facchinm** [comment]
Indeed, it's fixed by the toolchain update to 7-2017q4

**Comment by dsyleixa** [comment]
@sandeepmistry 
> 
> This core only supports the SAMD21 Cortex-M0 based boards.

is that/which is  true?
@facchinm wrote: 

> 
> 
> Indeed, it's fixed by the toolchain update to 7-2017q4

**Comment by facchinm** [comment]
It works in all architectures where the new toolchain is used (M0 for samd, M4 for nrf52-mbed)

**Comment by dsyleixa** [comment]
how to download this 7-2017q4 version?

**Comment by facchinm** [comment]
It's included in latest samd core (from 1.8.1 onwards)
